# Generated by Django 3.2.3 on 2025-01-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20250127_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure_unit',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
    ]
