# Generated by Django 3.2.3 on 2025-01-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_auto_20250128_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='quantity',
            new_name='amount',
        ),
    ]
