# Generated by Django 3.2.3 on 2025-01-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0008_auto_20250129_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
