# Generated by Django 3.2.3 on 2025-01-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0009_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество добавлений в избранное'),
        ),
    ]
