# Generated by Django 3.2.3 on 2025-02-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0013_auto_20250201_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='short_link',
            field=models.URLField(blank=True, db_index=True, unique=True),
        ),
    ]
