# Generated by Django 3.2.3 on 2025-02-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0016_auto_20250202_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
