# Generated by Django 3.2.3 on 2025-02-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0019_alter_recipeingredients_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='full_url',
        ),
        migrations.AddField(
            model_name='tokens',
            name='recipe',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='foodgram.recipe', verbose_name='рецепт'),
            preserve_default=False,
        ),
    ]
