# Generated by Django 3.2.3 on 2025-02-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0020_auto_20250212_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='short_link',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
