# Generated by Django 3.2.3 on 2025-02-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0021_alter_tokens_short_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
