# Generated by Django 3.2.3 on 2025-01-30 08:11

from django.db import migrations, models
from django.contrib.auth import validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250130_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(help_text='Обязательное поле. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[validators.UnicodeUsernameValidator()], verbose_name='Логин'),
        ),
    ]
